### ISSUE TITLE
Add session status

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-filebrowser#20]
Use the `INotebookSessionManager` from the `jupyter-js-services` refactor to get the status of the notebooks in the current directory, and add icons.

``` css
.notebook_icon:before {
    .icon(@fa-var-book);
    position: relative;
    top: -1px;
}

.running_notebook_icon:before {
    .icon(@fa-var-book);
    position: relative;
    top: -1px;
    color: @brand-success;
}
```
